openapi: 3.0.0
info:
    title: Ratings API
    version: 1.0.0
components:
    schemas:
        Rating:
            type: object
            properties:
                id:
                    type: string
                value:
                    type: string
                    enum:
                        - negative
                        - neutral
                        - positive
