template: |
  ## What's Changed

  $CHANGES
categories:
  - title: '💥 Breaking'
    label: 'type/breaking'
  - title: '🚀 Features'
    label: 'type/feature'
  - title: '🐛 Bug Fixes'
    label: 'type/bug'
  - title: '🧹 Housekeeping'
    label: 'type/housekeeping'
  - title: '🌍 Translations'
    label: 'type/translations'
  - title: '📦 Dependency Updates'
    label: 'type/dependencies'
    collapse-after: 5
change-template: '* (#$NUMBER) $TITLE - @$AUTHOR'
exclude-labels:
  - 'meta/skip-change-log'
