name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update-release-draft:
    permissions:
      contents: write
    uses: thulium/github-internals/.github/workflows/thulium-update-microservice-release-log.yml@main
    secrets: inherit
