name: Create Single openAPI page

on:
    push:
        branches: 'master'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions: write-all
        env:
            GITHUB_TOKEN_CI_CD: ${{ secrets.GH_ACCESS_TOKEN }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  registry-url: 'https://npm.pkg.github.com'
                  cache-dependency-path: packages/node

            - name: install Node dependencies
              run: |
                  npm i

            - name: test
              run: |
                  npm run test

            - name: publish NPM
              run: make publish-node
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
