name: Synchronize labels

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

jobs:
  synchronize:
    uses: thulium/github-internals/.github/workflows/thulium-synchronize-labels.yml@main
    secrets: inherit
